/*
 * RulesSuite.java
 * JUnit based test
 *
 * Created on November 27, 2007, 6:02 PM
 */

package com.formsdirectinc.rules;

import junit.framework.*;

/**
 *
 * @author rajesh
 */
public class RulesSuite extends TestCase {
    
    public RulesSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("RulesSuite");
        suite.addTest(com.formsdirectinc.rules.RuleEngineTest.suite());
        return suite;
    }

    public static void main(java.lang.String[] argList) {
        junit.textui.TestRunner.run(suite());
    }
    
}
