/*
 * InteractionSuite.java
 * JUnit based test
 *
 * Created on November 27, 2007, 6:03 PM
 */

package com.formsdirectinc.ui.interaction;

import junit.framework.*;

/**
 *
 * @author rajesh
 */
public class InteractionSuite extends TestCase {
    
    public InteractionSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("InteractionSuite");
        suite.addTest(com.formsdirectinc.ui.interaction.InteractionMgrTest.suite());
        suite.addTest(com.formsdirectinc.ui.interaction.helpers.HelpersSuite.suite());
        return suite;
    }

    public static void main(java.lang.String[] argList) {
        junit.textui.TestRunner.run(suite());
    }
    
}
