/*
 * XaoSuite.java
 * JUnit based test
 *
 * Created on May 6, 2008, 1:35 PM
 */

package com.formsdirectinc.xao;

import junit.framework.*;

/**
 *
 * @author rajesh
 */
public class XaoSuite extends TestCase {
    
    public XaoSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("XaoSuite");
        suite.addTest(com.formsdirectinc.xao.ApplicationXAOTest.suite());
        suite.addTest(com.formsdirectinc.xao.JAXBXAOTest.suite());
        suite.addTest(com.formsdirectinc.xao.UserDataXAOTest.suite());
        return suite;
    }

    public static void main(java.lang.String[] argList) {
        junit.textui.TestRunner.run(suite());
    }
    
}
