/*
 * ComparatorSuite.java
 * JUnit based test
 *
 * Created on May 6, 2008, 1:35 PM
 */

package com.formsdirectinc.ui.appcenter.comparator;

import junit.framework.*;

/**
 *
 * @author rajesh
 */
public class ComparatorSuite extends TestCase {
    
    public ComparatorSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ComparatorSuite");
        suite.addTest(com.formsdirectinc.ui.appcenter.comparator.FormNameComparatorTest.suite());
        suite.addTest(com.formsdirectinc.ui.appcenter.comparator.ApplicationStatusComparatorTest.suite());
        suite.addTest(com.formsdirectinc.ui.appcenter.comparator.ApplicantNameComparatorTest.suite());
        suite.addTest(com.formsdirectinc.ui.appcenter.comparator.ApplicationNameComparatorTest.suite());
        return suite;
    }

    public static void main(java.lang.String[] argList) {
        junit.textui.TestRunner.run(suite());
    }
    
}
