/*
 * ImplSuite.java
 * JUnit based test
 *
 * Created on November 27, 2007, 6:03 PM
 */

package com.jenkov.prizetags.tree.impl;

import junit.framework.*;

/**
 *
 * @author rajesh
 */
public class ImplSuite extends TestCase {
    
    public ImplSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ImplSuite");
        suite.addTest(com.jenkov.prizetags.tree.impl.TreeTest.suite());
        return suite;
    }

    public static void main(java.lang.String[] argList) {
        junit.textui.TestRunner.run(suite());
    }
    
}
