/*
 * SecuritySuite.java
 * JUnit based test
 *
 * Created on November 27, 2007, 6:03 PM
 */

package com.formsdirectinc.security;

import junit.framework.*;

/**
 *
 * @author rajesh
 */
public class SecuritySuite extends TestCase {
    
    public SecuritySuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("SecuritySuite");
        suite.addTest(com.formsdirectinc.security.AESUtilsTest.suite());
        suite.addTest(com.formsdirectinc.security.KeyGeneratorTest.suite());
        return suite;
    }

    public static void main(java.lang.String[] argList) {
        junit.textui.TestRunner.run(suite());
    }
    
}
