/*
 * MailSuite.java
 * JUnit based test
 *
 * Created on November 27, 2007, 6:02 PM
 */

package com.formsdirectinc.helpers.mail;

import junit.framework.*;

/**
 *
 * @author rajesh
 */
public class MailSuite extends TestCase {
    
    public MailSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("MailSuite");
        suite.addTest(com.formsdirectinc.helpers.mail.UIMessageResourceTest.suite());
        suite.addTest(com.formsdirectinc.helpers.mail.MailerTest.suite());
        return suite;
    }

    public static void main(java.lang.String[] argList) {
        junit.textui.TestRunner.run(suite());
    }
    
}
